"""add image_url to links

Revision ID: 347749b5eec3
Revises: ecdb19dd9f7d
Create Date: 2025-12-23 21:01:50.981154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347749b5eec3'
down_revision: Union[str, Sequence[str], None] = 'ecdb19dd9f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'image_url')
    # ### end Alembic commands ###
