"""archives_to_pdf_and_text

Revision ID: 402570471d93
Revises: c8b9d0e1f2a3
Create Date: 2026-01-07 12:58:22.848530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402570471d93'
down_revision: Union[str, Sequence[str], None] = 'c8b9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_pages', sa.Column('pdf_file_path', sa.String(length=255), nullable=True))
    op.add_column('archived_pages', sa.Column('full_text', sa.Text(), nullable=True))
    op.add_column('archived_pages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.drop_column('archived_pages', 'content_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_pages', sa.Column('content_file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('archived_pages', 'is_read')
    op.drop_column('archived_pages', 'full_text')
    op.drop_column('archived_pages', 'pdf_file_path')
    # ### end Alembic commands ###
