"""Add recent tracking fields

Revision ID: ecdb19dd9f7d
Revises: 637630c1ff38
Create Date: 2025-12-14 14:21:53.350340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecdb19dd9f7d'
down_revision: Union[str, Sequence[str], None] = '637630c1ff38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_clicked', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('click_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('notes', sa.Column('last_viewed', sa.DateTime(), nullable=True))
    
    # Fill null tags before setting not null
    op.execute("UPDATE notes SET tags = '[]' WHERE tags IS NULL")
    
    op.alter_column('notes', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('notes', 'last_viewed')
    op.drop_column('links', 'click_count')
    op.drop_column('links', 'last_clicked')
    # ### end Alembic commands ###
